### ISSUE TITLE
Menu item disabled in ST3

### ISSUE THREAD

**Issue by icio** [icio/sublime-text-marked#2]
Following the report in jocelynmallon/sublime-text-2-marked#6 it appears that there's an issue with the menu item being disabled in ST3. @potsky Did you install using package control? Also, did I miss a link to the old repository that lead you to filing the bug there?

Could be related to #1.

**Comment by nebhale** [comment]
I've just encountered the same issue using Package Control.  Anything I can do to help you diagnose the problem further?

**Comment by potsky** [comment]
Hi,

now I just use a shortcut to launch Marked.
1. I have created in my `ST3 Library / User /` folder the file `Marked.py` (https://gist.github.com/potsky/90ba39e15ea9284348f2)
2. Then I have added this shortcut : `{ "keys": ["super+alt+m"], "command": "marked" },`

It is faster.

**Comment by btmills** [comment]
This issue has also been bothering me (ST3, Package Control). Is there any diagnosis we can do?

**Comment by icio** [comment]
Hi all, I've submitted https://github.com/wbond/package_control_channel/pull/2525 to address this issue (and https://github.com/wbond/package_control_channel/pull/2524). In the mean time, OS X users can quite simply: 

``` bash
mv ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/Marked.app\ Menu.sublime-package ~/Library/Application\ Support/Sublime\ Text\ 3/Installed\ Packages/Marked\ App\ Menu.sublime-package
```

**Comment by icio** [comment]
Fixed. Apologies for the inconvenience @nebhale, @potsky, and @btmills, and thanks for getting in touch.
