### ISSUE TITLE
Latest version of Marked 2 is named "Marked 2" by default, how do I get it to work with "sublime-text-marked"?

### ISSUE THREAD

**Issue by jonathanmorgan** [icio/sublime-text-marked#3]
Hi,

The latest version of Marked 2 (2.3, I believe), ships named "Marked 2", not simply "Marked".  I tried renaming it to "Marked" in the applications folder, but that didn't make it work.  Any idea what I need to do to get it working again?

Thanks,

Jon Morgan

**Comment by jonathanmorgan** [comment]
Ah.  Well, renaming to "Marked" from "Marked 2" is working now.  So, guess this is just an FYI that the name changed, and you might need to restart Sublime and your computer to get everything sorted out after you install latest Marked 2 then rename.  Not sure how it will behave after being updated, either, but we'll see.

**Comment by icio** [comment]
Thanks, @jonathanmorgan, I eventually became aware of the new Marked release and am yet to upgrade. I'll upgrade and try to implement support for both.

**Comment by stefanscheidt** [comment]
+1 for support for "Marked 2". I just don't want to rename "Marked 2.app" to "Marked.app" if possible ...

**Comment by jonathanmorgan** [comment]
One option that is working for me is to remove the old "Marked.app" folder if it is still there, then make a symlink to "Marked\ 2.app" in the /Applications folder named "Marked.app":

```
# in shell, change directories into /Applications
cd /Applications

# remove "Marked" if it is already there.
sudo rm -rf Marked.app

# Make symbolic link to "Marked 2.app" named "Marked.app".
ln -s /Applications/Marked\ 2.app Marked.app
```

**Comment by icio** [comment]
Hi everyone, thanks for the comments and apologies for not moving too quickly on this. I put down my ten bucks to test out patches. I've just submitted https://github.com/icio/sublime-text-marked/pull/5 which should support both versions.

**Comment by stefanscheidt** [comment]
Works great for me. Thanks!!!

**Comment by kerrizor** [comment]
Ideally, it could check for Marked 2, then fall back to Marked?

**Comment by icio** [comment]
That's what https://github.com/icio/sublime-text-marked/pull/5 implemented, @kerrizor. I believe this feature to be working, but please open another issue if I am mistaken.
